cinema/config/routes.rb
Rails.application.routes.draw do
  resources :estrenos

end

cinema/app/models/estreno.rb
class Estreno < ActiveRecord::Base
end

cinema/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

cinema/app/controllers/estrenos_controller.rb
class EstrenosController < ApplicationController
  before_action :set_estreno, only: [:show, :edit, :update, :destroy]

  # GET /estrenos
  # GET /estrenos.json
  def index
    @estrenos = Estreno.all
  end

  # GET /estrenos/1
  # GET /estrenos/1.json
  def show
  end

  # GET /estrenos/new
  def new
    @estreno = Estreno.new
  end

  # GET /estrenos/1/edit
  def edit
  end

  # POST /estrenos
  # POST /estrenos.json
  def create
    @estreno = Estreno.new(estreno_params)

    respond_to do |format|
      if @estreno.save
        format.html { redirect_to @estreno, notice: 'Estreno creado exitosamente.' }
        format.json { render :show, status: :created, location: @estreno }
      else
        format.html { render :new }
        format.json { render json: @estreno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estrenos/1
  # PATCH/PUT /estrenos/1.json
  def update
    respond_to do |format|
      if @estreno.update(estreno_params)
        format.html { redirect_to @estreno, notice: 'Estreno actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @estreno }
      else
        format.html { render :edit }
        format.json { render json: @estreno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estrenos/1
  # DELETE /estrenos/1.json
  def destroy
    @estreno.destroy
    respond_to do |format|
      format.html { redirect_to estrenos_url, notice: 'Estreno eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estreno
      @estreno = Estreno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estreno_params
      params.require(:estreno).permit(:Nombre, :Hora, :Sala, :Oferta)
    end
end

cinema/app/helpers/application_helper.rb
module ApplicationHelper
end

cinema/app/helpers/estrenos_helper.rb
module EstrenosHelper
end

cinema/app/views/estrenos/_form.html.erb
<%= form_for(@estreno) do |f| %>
  <% if @estreno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estreno.errors.count, "error") %> prohibited this estreno from being saved:</h2>

      <ul>
      <% @estreno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Hora %><br>
    <%= f.time_select :Hora %>
  </div>
  <div class="field">
    <%= f.label :Sala %><br>
    <%= f.number_field :Sala %>
  </div>
  <div class="field">
    <%= f.label :Oferta %><br>
    <%= f.check_box :Oferta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cinema/app/views/estrenos/edit.html.erb
<h1>Editing estreno</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @estreno %> |
<%= link_to 'Volver', estrenos_path %>

cinema/app/views/estrenos/index.html.erb
<h1><font Color = Green>Estrenos</font></h1>
<h2><font Color = blue>Disfruta en Familia de todos nuestros Estrenos</font></h2>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Hora</th>
      <th>Sala</th>
      <th>Oferta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estrenos.each do |estreno| %>
      <tr>
        <td><%= estreno.Nombre %></td>
        <td><%= estreno.Hora %></td>
        <td><%= estreno.Sala %></td>
        <td><%= estreno.Oferta %></td>
        <td><%= link_to 'Mostrar', estreno %></td>
        <td><%= link_to 'Editar', edit_estreno_path(estreno) %></td>
        <td><%= link_to 'Borrar', estreno, method: :delete, data: { confirm: 'Seguro de Borrar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar Estreno', new_estreno_path %>

cinema/app/views/estrenos/new.html.erb
<h1>Agregar Estreno</h1>

<%= render 'form' %>

<%= link_to 'Volver', estrenos_path %>

cinema/app/views/estrenos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @estreno.Nombre %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @estreno.Hora %>
</p>

<p>
  <strong>Sala:</strong>
  <%= @estreno.Sala %>
</p>

<p>
  <strong>Oferta:</strong>
  <%= @estreno.Oferta %>
</p>

<%= link_to 'Editar', edit_estreno_path(@estreno) %> |
<%= link_to 'Volver', estrenos_path %>

cinema/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cinema</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>